# Wokwi simulation configuration for PetFilter firmware
# See: https://docs.wokwi.com/vscode/project-config
[wokwi]
version = 1
# Firmware binary produced by `cargo build --release`
# Use `espflash save-image` or `idf.py uf2` to generate
firmware = ".wokwi-host/petfilter"
elf = ".wokwi-host/petfilter.elf"

# GDB debugging support
# gdbServerPort = 3333
